"""DB-backed escalation glue for the workflow runner (WP-12).

`orchestrator/workflow/runner.py` stays repository-import-free by design (hard
invariant: the `workflow/` package is pure except for this module, which is
the one place allowed to talk to Postgres). This module owns:

  * consulting/creating `pending_actions` rows (repository.py's CRUD, WP-11),
  * sending the orchestration-team comms notification, and
  * exposing a `(action, phase) -> "approved"|"pending"` closure shaped
    exactly like `runner.EscalationCallback`, so callers (verify_run,
    `_apply_in_worktree` — WP-08/09/13) can wire it straight into
    `run_step(..., escalation_cb=...)`.

Discriminator (Gate A opus QA finding 4b)
------------------------------------------
An escalation can happen for two different reasons that look identical to an
approver unless labeled:

  * `phase="authorize"` — the action has never run; permissions.authorize()
    returned "escalate" before execution was attempted. Approving means
    "let this run for the first time."
  * `phase="on_fail"` — the action DID run and failed, and its `on_fail` is
    "escalate". Approving means "retry it."

`pending_actions` (migration 0022) has no spare column for this — `action_kind`
is already `run|builtin`, and adding a column means a new migration, which is
out of scope for this WP. Per the Gate A adjustment, `phase` is instead folded
into the `requested_by` string (see `_tag_phase`) — the only slot available
without a migration — and spelled out in full in both the `action_escalated`
issue_events payload (which is generated by `create_pending_action` from its
`requested_by` argument) and the comms message body. `list_pending_actions`/
the future `/actions` dashboard (WP-15) and any human reader therefore always
see WHY an action is waiting, not just WHAT is waiting.
"""

from __future__ import annotations

from typing import Any, Optional

from orchestrator import repository as repo
from .models import RequiredAction

EscalationHandler = Any  # Callable[[RequiredAction, str], str]; see runner.EscalationCallback

# Human-readable explanation per phase, used in the comms message body so an
# approver never has to guess what approving actually does.
_PHASE_EXPLANATION = {
    "authorize": (
        "this action has not run yet; it requires approval before it may run "
        "for the first time"
    ),
    "on_fail": (
        "this action already ran and FAILED; approving will retry it"
    ),
}


def _phase_explanation(phase: str) -> str:
    return _PHASE_EXPLANATION.get(phase, f"phase={phase}")


def _tag_phase(requested_by: str, phase: str) -> str:
    """Fold `phase` into the `requested_by` string for storage.

    `pending_actions.action_kind` is already used for run|builtin, and this WP
    may not add a migration, so `requested_by` is the cleanest existing slot:
    it flows automatically into the `action_escalated` issue_events payload
    (via `create_pending_action`) and is visible on the row itself (and, once
    WP-15 lands, the dashboard). The raw requester is preserved verbatim with a
    trailing `(phase:<phase>)` tag; a reader can still see who/what requested
    it, plus why it's waiting.
    """
    tag = f"(phase:{phase})"
    return f"{requested_by} {tag}".strip() if requested_by else tag


def _action_identity(action: RequiredAction) -> tuple[str, str]:
    """Return (action_str, action_kind) for a RequiredAction, exactly as it
    should be stored/matched in pending_actions: builtin name for a builtin
    action, exact run string otherwise."""
    if action.builtin:
        return action.builtin, "builtin"
    return action.run, "run"


def _newest_denied_row(
    pool: Any, issue_id: int, step: str, action_str: str,
) -> Optional[dict[str, Any]]:
    """Newest `denied` row matching (issue_id, step, action_str), or None.

    No repository query exists for "denied" specifically (only
    `find_approved_action`), so this filters `list_pending_actions(status=
    "denied")` client-side — the same pattern the pending-dedup check below
    already uses for `status="pending"`."""
    matching = [
        row for row in repo.list_pending_actions(pool, status="denied")
        if row["issue_id"] == issue_id and row["step"] == step and row["action"] == action_str
    ]
    if not matching:
        return None
    return max(matching, key=lambda row: row["created_at"])


def handle_escalation(
    pool: Any,
    issue_id: Optional[int],
    worktree: str,
    step: str,
    action_str: str,
    action_kind: str,
    requested_by: str,
    phase: str,
) -> str:
    """Resolve one escalating action against `pending_actions` + comms.

    1. An already-`approved` row matching (issue_id, step, action_str) exists,
       and no NEWER `denied` row exists for the same triple -> consume it
       (one-shot: it moves to `executed`) and return "approved" so the runner
       executes the action now.
    2. A `denied` row matching the same triple exists (and is not older than
       any matching `approved` row — newest resolution wins) -> return
       "denied". A denial is a hard stop: unlike a pending escalation it is
       terminal and does NOT re-escalate (no new `pending` row is created for
       this triple), so this check runs BEFORE the pending-dedup check below
       and short-circuits it. The runner turns "denied" into a real failed
       step naming the denial (see `orchestrator/workflow/runner.py`) — the
       corresponding gate/verify-run mapping to a failure (not another
       "blocked_on_approval") lives in the two call sites (WP-13).
    3. An identical row is already `pending` (same issue/step/action) -> return
       "pending" without creating a duplicate row or sending a duplicate
       message (a step may be re-run, e.g. by a retrying worker, while the
       first escalation is still awaiting a human).
    4. Otherwise: create a new pending row (tagging `requested_by` with
       `phase`, see `_tag_phase`) and send a `high`-priority comms message to
       the `orchestration` team explaining what's blocked and why. Return
       "pending".

    Args:
        pool: DB connection pool.
        issue_id: the escalating issue, or None for an issue-less run (the
            pending row and event log are simply not issue-scoped then; a
            `None` issue_id also has no way to look up prior approved/denied
            rows, so it always falls through to creating a fresh pending row —
            matching the pre-existing behavior for approved/pending lookups).
        worktree: checkout root the action would run against.
        step: workflow step name (e.g. "prepare", "verify").
        action_str: exact resolved run string, or builtin name.
        action_kind: "run" | "builtin".
        requested_by: caller-supplied identity for the escalation (e.g. the
            worker/role that hit it); may be "".
        phase: "authorize" | "on_fail" — see module docstring.

    Returns:
        "approved" (runner should execute the action now), "denied" (runner
        should fail the step, naming the denial), or "pending" (runner should
        block the step as `blocked_on_approval`).
    """
    if issue_id is not None:
        approved = repo.find_approved_action(pool, issue_id, step, action_str)
        denied = _newest_denied_row(pool, issue_id, step, action_str)

        if approved is not None and (denied is None or approved["created_at"] >= denied["created_at"]):
            try:
                repo.consume_approved_action(pool, approved["id"])
                return "approved"
            except ValueError:
                # Concurrent-consume race: another worker consumed this row between
                # our find_approved_action and consume. The UPDATE is atomic (only
                # updates if status='approved'), so the loser simply gets ValueError.
                # Return "pending" so the loser re-escalates cleanly on its next poll —
                # same behavior as an already-consumed approval.
                return "pending"

        if denied is not None:
            return "denied"

        for row in repo.list_pending_actions(pool, status="pending"):
            if (
                row["issue_id"] == issue_id
                and row["step"] == step
                and row["action"] == action_str
            ):
                return "pending"

    tagged_requested_by = _tag_phase(requested_by, phase)
    repo.create_pending_action(
        pool,
        issue_id=issue_id,
        worktree=worktree,
        step=step,
        action=action_str,
        action_kind=action_kind,
        requested_by=tagged_requested_by,
        phase=phase,
    )

    issue = repo.get_issue(pool, issue_id) if issue_id is not None else None
    from_team = issue.team if issue is not None else "engine"
    body = (
        f"Issue #{issue_id if issue_id is not None else '(none)'} step '{step}' "
        f"is blocked_on_approval.\n"
        f"Phase: {phase} — {_phase_explanation(phase)}.\n"
        f"Worktree: {worktree}\n"
        f"Action ({action_kind}): {action_str}\n"
        f"Requested by: {requested_by or '(unspecified)'}"
    )
    repo.create_message(
        pool,
        from_team=from_team,
        to_team="orchestration",
        subject=f"Action approval needed: {step}/{action_str[:60]}",
        body=body,
        priority="high",
        issue_id=issue_id,
    )
    return "pending"


def make_escalation_cb(
    pool: Any,
    issue_id: Optional[int],
    worktree: str,
    step: str,
    requested_by: str,
):
    """Build a `(action, phase) -> "approved"|"pending"` closure for `run_step`.

    NOTE on `step`: the WP-12 spec text lists this factory as
    `make_escalation_cb(pool, issue_id, worktree, requested_by)` (no `step`).
    That signature can't actually work: `run_step` is invoked once per
    step_name (e.g. "prepare", then separately "verify"), and
    `handle_escalation` needs `step` to match/dedupe `pending_actions` rows
    correctly (the CRUD's `find_approved_action`/pending-dedup lookups are
    keyed on (issue_id, step, action)). Since a caller (WP-13) already knows
    which step it's about to run before calling `run_step`, `step` is added
    here as an explicit parameter — this factory is meant to be (re)built once
    per `run_step` call, one per step. Documenting this deviation per the
    monitor's instruction to record such choices.

    Returns:
        A callable `(action: RequiredAction, phase: str) -> str` suitable for
        `run_step`'s `escalation_cb` parameter.
    """

    def _cb(action: RequiredAction, phase: str) -> str:
        action_str, action_kind = _action_identity(action)
        return handle_escalation(
            pool,
            issue_id,
            worktree,
            step,
            action_str,
            action_kind,
            requested_by,
            phase,
        )

    return _cb
