"""Onboarding helpers — pure policy for `orchestrator init` / `orchestrator doctor`.

Kept I/O-free (like decomposition / pipelines / state_machine) so the choices are
unit-testable: tier recommendation from a fleet's model names, the drop-in instance
config a bootstrap writes, and the doctor check model + PASS/WARN/FAIL summary. The
CLI performs the actual DB / config / registration side effects around these.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import yaml

from . import decomposition

# --------------------------------------------------------------------------- #
# Tier recommendation from a fleet's models
#
# A fleet is only as reliable as its weakest worker, so the rule is conservative:
#   * ANY small / low-reliability model present            -> remedial
#   * every model strong AND a top-tier model present      -> high  (internal
#                                                             parallelism pays off)
#   * otherwise                                            -> mid
# This is a RECOMMENDATION the operator overrides with --decomposition-tier.
# --------------------------------------------------------------------------- #

_REMEDIAL_SIGNS = ("qwen", "-7b", "-8b", "-3b", "-2b", "1.5b", "1_5b", "0.5b",
                   "gemma", "phi-", "phi3", "tinyllama", "llama-2", "llama2",
                   "mistral-7b", "codellama-7b")
_STRONG_SIGNS = ("opus", "sonnet", "haiku", "gpt-4", "gpt-5", "deepseek",
                 "fable", "qwen-max", "qwen2.5-72b", "qwen-plus")
_TOP_SIGNS = ("opus", "gpt-5", "fable", "gpt-4.1", "deepseek-v4-pro", "deepseek-r1")


def _matches(name: str, signs: tuple[str, ...]) -> bool:
    return any(s in name for s in signs)


def recommend_tier(models: list[str]) -> str:
    """Recommend a decomposition tier from the fleet's model names (a heuristic;
    always overridable). Empty/unknown → the default (mid)."""
    names = [m.lower() for m in models if m]
    if not names:
        return decomposition.DEFAULT_TIER
    # qwen-max/plus are strong despite the 'qwen' stem — check the strong-and-not
    # -remedial case per model so 'qwen-local' → remedial but 'qwen-max' does not.
    def is_remedial(n: str) -> bool:
        if _matches(n, _STRONG_SIGNS):
            return False
        return _matches(n, _REMEDIAL_SIGNS) or n in ("qwen", "qwen-local")
    if any(is_remedial(n) for n in names):
        return decomposition.REMEDIAL
    if all(_matches(n, _STRONG_SIGNS) for n in names) and any(_matches(n, _TOP_SIGNS) for n in names):
        return decomposition.HIGH
    return decomposition.MID


# --------------------------------------------------------------------------- #
# Drop-in instance config (config/instances.d/<project>.yaml)
#
# init writes a standalone file rather than editing the curated, commented
# instances.yaml. config.load_settings merges config/instances.d/*.yaml over it.
# --------------------------------------------------------------------------- #

def build_instance_entry(*, label: str, database_url: str, roster_file: str,
                         tier: str, extra_settings: dict | None = None) -> dict:
    """The instance mapping value (matches an instances.yaml entry)."""
    # `workflow_profile: legacy` is written explicitly so the operator can see
    # and flip the Workflow Profile cutover toggle; legacy is today's behavior.
    settings: dict = {"decomposition_tier": tier, "workflow_profile": "legacy"}
    if extra_settings:
        settings.update(extra_settings)
    return {
        "label": label,
        "database_url": database_url,
        "roster_file": roster_file,
        "settings": settings,
    }


def render_instances_dropin(project: str, entry: dict) -> str:
    """Render the drop-in file body: `{instances: {<project>: <entry>}}`."""
    header = (f"# Generated by `orchestrator init` for project {project!r}.\n"
              "# Merged over config/instances.yaml by config.load_settings.\n")
    body = yaml.safe_dump({"instances": {project: entry}}, sort_keys=False)
    return header + body


# --------------------------------------------------------------------------- #
# Doctor: preflight check model + summary
# --------------------------------------------------------------------------- #

PASS = "pass"
WARN = "warn"
FAIL = "fail"

_MARK = {PASS: "✓", WARN: "!", FAIL: "✗"}


@dataclass
class Check:
    name: str
    status: str
    detail: str = ""


def summarize(checks: list[Check]) -> tuple[int, str]:
    """Render a checklist and an exit code: non-zero iff any check FAILED (a WARN
    never fails the run — it is guidance, not a blocker)."""
    lines = [f"  {_MARK.get(c.status, '?')} {c.name}: {c.status.upper()}"
             + (f" — {c.detail}" if c.detail else "")
             for c in checks]
    n_fail = sum(1 for c in checks if c.status == FAIL)
    n_warn = sum(1 for c in checks if c.status == WARN)
    verdict = "NOT READY" if n_fail else ("READY (with warnings)" if n_warn else "READY")
    footer = f"\n{verdict} — {len(checks)} checks, {n_fail} failed, {n_warn} warning(s)."
    return (1 if n_fail else 0), "\n".join(lines) + footer
