"""Code-generation provider factory.

The code agent is fully configurable. Default `stub` returns deterministic
placeholder output and needs no network, so the full pipeline is verifiable
in-cloud without any external endpoint. `openai` targets any OpenAI-compatible
endpoint via base_url; `anthropic` reuses the Anthropic SDK.

NOTE: the Qwen box 10.100.90.132:8081 is a private LAN IP, unreachable from the
Anthropic cloud env. Point `openai` at a publicly reachable endpoint (added to
the environment's Custom allowed domains) or run via a teleported local session.
"""

from __future__ import annotations

from typing import Protocol

from ..config import Settings
from .base import CodeResult

_CODE_SYSTEM = (
    "You are a code-generation agent in an orchestrated pipeline. Produce only "
    "the code or unified diff requested. Do not include commentary."
)


class CodeClient(Protocol):
    def generate(self, prompt: str) -> CodeResult: ...


class StubCodeClient:
    """Deterministic placeholder generator — no network."""

    def generate(self, prompt: str) -> CodeResult:
        content = (
            "# --- generated by stub code provider (not executed) ---\n"
            f"# request: {prompt.strip()[:200]}\n"
            "def placeholder():\n"
            "    raise NotImplementedError('stub provider output')\n"
        )
        return CodeResult(content=content, provider="stub", model="stub")


class OpenAICodeClient:
    def __init__(self, settings: Settings):
        from openai import OpenAI

        self._model = settings.code_model or "gpt-4o-mini"
        self._client = OpenAI(
            base_url=settings.code_base_url or None,
            api_key=settings.code_api_key or "not-needed",
        )

    def generate(self, prompt: str) -> CodeResult:
        resp = self._client.chat.completions.create(
            model=self._model,
            messages=[
                {"role": "system", "content": _CODE_SYSTEM},
                {"role": "user", "content": prompt},
            ],
        )
        return CodeResult(
            content=resp.choices[0].message.content or "",
            provider="openai",
            model=self._model,
        )


class AnthropicCodeClient:
    def __init__(self, settings: Settings):
        from anthropic import Anthropic

        self._model = settings.code_model or settings.reasoning_model
        self._client = Anthropic(api_key=settings.anthropic_api_key)

    def generate(self, prompt: str) -> CodeResult:
        resp = self._client.messages.create(
            model=self._model,
            max_tokens=2048,
            system=_CODE_SYSTEM,
            messages=[{"role": "user", "content": prompt}],
        )
        text = "".join(b.text for b in resp.content if getattr(b, "type", "") == "text")
        return CodeResult(content=text, provider="anthropic", model=self._model)


def make_code_client(settings: Settings) -> CodeClient:
    provider = (settings.code_provider or "stub").lower()
    if provider == "openai":
        return OpenAICodeClient(settings)
    if provider == "anthropic":
        return AnthropicCodeClient(settings)
    return StubCodeClient()
